name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests & Save Results
        run: npm test -- --json --outputFile=test-results.json || true

      - name: Upload Test Report (Artifact)
        uses: actions/upload-artifact@v3  # Correct syntax here
        with:
          name: test-results
          path: test-results.json
